from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split('''
CMSIS/Device/ST/STM32L4xx/Source/Templates/system_stm32l4xx.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_comp.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc_ex.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cryp.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cryp_ex.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_exti.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rng.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_usart.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_usart_ex.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c
STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c
''')

path = [
    cwd + '/CMSIS/Include',
    cwd + '/STM32L4xx_HAL_Driver/Inc',
    cwd + '/CMSIS/Device/ST/STM32L4xx/Include']

CPPDEFINES = ['STM32L431xx', 'USE_HAL_DRIVER', 'FM_USING_LIBC']

objs = DefineGroup('libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('objs')
