from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

objs = DefineGroup('nr_micro_shell', src, depend = ['NR_MICRO_SHELL_ENABLE'], CPPPATH = CPPPATH)

Return('objs')
