import os
from building import *
from gcc import *
Import('fmconfig')

group = []

newlib_version = GetNewLibVersion(fmconfig)

if newlib_version and not GetDepend('FM_USING_EXTERNAL_LIBC'):
    print('Newlib version: ' + newlib_version)

    cwd = GetCurrentDir()
    src = Glob('*.c')

    CPPPATH = [cwd]
    CPPDEFINES = ['FM_USING_NEWLIBC', 'FM_USING_LIBC', '_POSIX_C_SOURCE=1'] # identify this is Newlib, and only enable POSIX.1-1990
    LIBS = ['c', 'm'] # link libc and libm
    AddDepend(['FM_USING_NEWLIBC', 'FM_USING_LIBC'])

    group = group + DefineGroup('Compiler', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LIBS = LIBS)
Return('group')
