from building import *

cwd = GetCurrentDir()
src   = Glob('*.c')

if GetDepend('FM_USING_DEV_BUS_PLATFORM') == False:
    SrcRemove(src, ['platform.c'])

CPPPATH = [cwd + '/../include']

group = DefineGroup('drivers', src, depend = ['FM_USING_DEV_BUS'], CPPPATH = CPPPATH)

Return('group')
