#ifndef __FMCU_CONFIG_H__
#define __FMCU_CONFIG_H__

/* Generated by FMCU Configuration */

/* FMCU Kernel Configuration */

#define SECTION_ENABLE
#define DEBUG_ENABLE
#define DEBUG_BUF_SIZE 256
#define DEBUG_COLOR

/* end of FMCU Kernel Configuration */

/* FMCU Drivers Configuration */

#define DAL_DRIVERS_ENABLE
#define DAL_SYSTEM_ENABLE
#define DAL_SERIAL_ENABLE
#define DAL_IT_ENABLE
#define DAL_GPIO_ENABLE
#define DAL_FLASH_ENABLE
#define DAL_TIMER_ENABLE
#define DAL_PWM_ENABLE
#define DAL_SPI_ENABLE

/* end of FMCU Drivers Configuration */

/* FMCU Components Configuration */


/* end of FMCU Components Configuration */

#endif /* __FMCU_CONFIG_H__ */
