from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src += ['../libraries/CMSIS/GD/GD32E23x/Source/ARM/startup_gd32f3x0.s']

path = [cwd]

objs = DefineGroup('board', src, depend = [''], CPPPATH = path)

Return('objs')
