from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('nr_micro_shell', src, depend = ['NR_MICRO_SHELL_ENABLE'], CPPPATH = CPPPATH)

Return('group')
