import sys
import os

FM_ROOT = '../../../'
Export('FM_ROOT')

sys.path.append(FM_ROOT + 'tools')

try:
    from building import *
except:
    print('Cannot found RT-Thread root directory, please check RTT_ROOT')
    print()
    exit(-1)

from building import *

# Prase qkconfig.h to get depend
PrepareCreat()

# objs_utils = SConscript(os.path.join(FM_ROOT, 'utils', 'SConscript'))
objs_bsp = SConscript('SConscript')

# objs = objs_utils + objs_bsp

CreateProject('project.uvprojx')

exit(0)
