import sys
import os

FM_ROOT = '../../../'
Export('FM_ROOT')

sys.path.append(FM_ROOT + 'tools')

try:
    from building import *
except:
    print('Cannot found RT-Thread root directory, please check FM_ROOT')
    print()
    exit(-1)

SDK_ROOT = os.path.abspath('./')

if os.path.exists(SDK_ROOT + '/libraries'):
    libraries_path_prefix = SDK_ROOT + '/libraries'
else:
    libraries_path_prefix = os.path.dirname(SDK_ROOT) + '/libraries'

SDK_LIB = libraries_path_prefix
Export('SDK_LIB')

BSP_LIBRARY = 'STM32L4xx_HAL'
Export('BSP_LIBRARY')

# Prase fmconfig.h to get depend
PrepareCreate(FM_ROOT)

objs_bsp = SConscript('SConscript')

StartCreate()
