import os
from building import *

Import('FM_ROOT')
Import('SDK_LIB')
Import('BSP_LIBRARY')

cwd = GetCurrentDir()
objs = []

objs = objs + SConscript(os.path.join(FM_ROOT, 'SConscript'))
objs = objs + SConscript(os.path.join(SDK_LIB, BSP_LIBRARY, 'SConscript'))
objs = objs + SConscript(os.path.join(SDK_LIB, 'HAL_Drivers', 'SConscript'))

path =  [cwd]

# add rtconfig.h/BSP path into Kernel group
DefineGroup("src", [], [], CPPPATH=path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
