#ifndef __FMCU_CONFIG_H__
#define __FMCU_CONFIG_H__

/* Generated by FMCU Configuration */

/* FMCU Kernel Configuration */

#define SECTION_ENABLE
#define DEBUG_ENABLE
#define DEBUG_BUF_SIZE 256
#define TIMER_ENABLE
#define TIMER_RUN_SECTION

/* end of FMCU Kernel Configuration */

/* FMCU Drivers Configuration */

#define DAL_DRIVERS_ENABLE
#define DAL_SYSTEM_ENABLE
#define DAL_SERIAL_ENABLE
#define DAL_IT_ENABLE
#define DAL_GPIO_ENABLE
#define DAL_FLASH_ENABLE
#define DAL_TIMER_ENABLE
#define DAL_PWM_ENABLE
#define DAL_SPI_ENABLE
#define DAL_ADC_ENABLE
#define DAL_WDT_ENABLE

/* end of FMCU Drivers Configuration */

/* FMCU Components Configuration */


/* Network */


/* end of Network */

/* end of FMCU Components Configuration */

/* FMCU Drivers Config */

/* On-chip Peripheral Drivers */

#define MCU_USING_SYSTEM
#define MCU_USING_GPIO
#define MCU_USING_FLASH
#define MCU_USING_PWM
#define MCU_USING_SPI
#define MCU_USING_TIMER
#define MCU_USING_UART
#define MCU_USING_ADC
#define MCU_USING_WDT

/* end of On-chip Peripheral Drivers */

/* end of FMCU Drivers Config */

#endif /* __FMCU_CONFIG_H__ */
