import sys
import os

FM_ROOT = '../../../'
Export('FM_ROOT')

sys.path.append(FM_ROOT + 'tools')

try:
    from building import *
except:
    print('Cannot found RT-Thread root directory, please check FM_ROOT')
    print()
    exit(-1)

from building import *

# Prase fmconfig.h to get depend
PrepareCreate()

objs_bsp = SConscript('SConscript')

StartCreate()
