#ifndef __QKIT_CONFIG_H__
#define __QKIT_CONFIG_H__

/* Generated by FMCU Configuration */

/* FMCU Kernel Configuration */

#define SECTION_ENABLE
#define DEBUG_ENABLE
#define LOG_BUF_SIZE 512
#define LOG_LVL_DEBUG
#define MEMH_ENABLE
#define MEMH_BUF_SIZE 2048
#define TIMER_ENABLE
#define FIFO_ENABLE

/* end of FMCU Kernel Configuration */

/* FMCU Examples Configuration */


/* end of FMCU Examples Configuration */

/* FMCU Drivers Configuration */

#define DAL_DRIVERS_ENABLE
#define DAL_SYSTEM_ENABLE
#define DAL_SERIAL_ENABLE
#define DAL_IT_ENABLE
#define DAL_GPIO_ENABLE
#define DAL_FLASH_ENABLE
#define DAL_TIMER_ENABLE

/* end of FMCU Drivers Configuration */

#endif /* __QKIT_CONFIG_H__ */
