#ifndef __QKIT_CONFIG_H__
#define __QKIT_CONFIG_H__

/* Generated by QKit Configuration */

/* QKit Utils Configuration */

#define FIFO_ENABLE
#define DEBUG_ENABLE
#define LOG_BUF_SIZE 512
#define LOG_LVL_DEBUG
#define MEMH_ENABLE
#define MEMH_BUF_SIZE 2048
#define TIMER_ENABLE
#define TIMER_RUN_SECTION

/* end of QKit Utils Configuration */

#endif /* __QKIT_CONFIG_H__ */
