#ifndef __QKIT_CONFIG_H__
#define __QKIT_CONFIG_H__

/* Generated by QKit Configuration */

/* QKit Kernel Configuration */

#define SECTION_ENABLE
#define DEBUG_ENABLE
#define LOG_BUF_SIZE 512
#define LOG_LVL_DEBUG
#define MEMH_ENABLE
#define MEMH_BUF_SIZE 2048
#define TIMER_ENABLE
#define FIFO_ENABLE

/* end of QKit Kernel Configuration */

/* QKit Examples Configuration */

#define EXAMPLES_ENABLE
#define EXAMPLE_TIMER_ENABLE
#define EXAMPLE_MEMH_ENABLE

/* end of QKit Examples Configuration */

#endif /* __QKIT_CONFIG_H__ */
