import sys
import os

QK_ROOT = '../../../'
Export('QK_ROOT')

sys.path.append(QK_ROOT + 'tools')

try:
    from building import *
except:
    print('Cannot found RT-Thread root directory, please check RTT_ROOT')
    print()
    exit(-1)

from building import *

# objs_utils = SConscript(os.path.join(QK_ROOT, 'utils', 'SConscript'))
objs_bsp = SConscript('SConscript')

# objs = objs_utils + objs_bsp

CreateProject('project.uvprojx')

exit(0)
