from building import *

cwd = GetCurrentDir()
src = []

if GetDepend(['DAL_SYSTEM_ENABLE']):
    src += ['dal_system.c']

if GetDepend(['DAL_SERIAL_ENABLE']):
    src += ['dal_uart.c']
    
if GetDepend(['DAL_IT_ENABLE']):
    src += ['dal_it.c']

if GetDepend(['DAL_GPIO_ENABLE']):
    src += ['dal_gpio.c']

if GetDepend(['DAL_GPIO_ENABLE']):
    src += ['dal_flash.c']

path = [cwd + '/include']

objs = DefineGroup('dal', src, depend = ['DAL_DRIVERS_ENABLE'], CPPPATH = path)

Return('objs')