from building import *

cwd = GetCurrentDir()
src = []
path = [cwd + '/include']

if GetDepend(['FM_USING_SERIAL']):
    src += ['serial.c']

objs = DefineGroup('drivers', src, depend = ['FM_USING_DEVICE_DRIVERS'], CPPPATH = path)

Return('objs')
