from building import *

cwd = GetCurrentDir()
src = []

if GetDepend(['EXAMPLE_TIMER_ENABLE']):
    src += ['e_timer.c']

if GetDepend(['EXAMPLE_MEMH_ENABLE']):
    src += ['e_memh.c']

path = [cwd]

objs = DefineGroup('examples', src, depend = ['EXAMPLES_ENABLE'], CPPPATH = path)

Return('objs')