from building import *

cwd = GetCurrentDir()
src = Split("""
i2c_core.c
i2c_dev.c
""")

if GetDepend('FM_USING_I2C_BITOPS'):
    src = src + ['i2c-bit-ops.c']
if GetDepend('FM_USING_SOFT_I2C'):
    src = src + ['soft_i2c.c']

# The set of source files associated with this SConscript file.
path = [cwd + '/../include']

group = DefineGroup('drivers', src, depend = ['FM_USING_I2C'], CPPPATH = path)

Return('group')
