from building import *

cwd     = GetCurrentDir()
src     = Glob('src/*.c') + Glob('port/*.c')
CPPPATH = [cwd + '/inc',
           cwd + '/port']

group = DefineGroup('sfud', src, depend = ['SFUD_ENABLE'], CPPPATH = CPPPATH)

Return('group')
