from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
CMSIS/Device/ST/STM32G0xx/Source/Templates/system_stm32g0xx.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cec.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cortex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_gpio.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_usart_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_spi.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_tim.c
""")

path = [
    cwd + '/CMSIS/Include',
    cwd + '/STM32G0xx_HAL_Driver/Inc',
    cwd + '/CMSIS/Device/ST/STM32G0xx/Include']

CPPDEFINES = ['STM32G030xx', 'USE_HAL_DRIVER']

objs = DefineGroup('libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('objs')
