from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd + '/../include']
group   = DefineGroup('drivers', src, depend = ['FM_USING_PIC'], CPPPATH = CPPPATH)

Return('group')
