from building import *

cwd = GetCurrentDir()
# src = Glob('*.c')
src = ['fm_section.c', 'fm_log.c']

path = [cwd + '/../include']

objs = DefineGroup('src', src, depend = [''], CPPPATH = path)

Return('objs')