from building import *

cwd = GetCurrentDir()
src = []

if GetDepend(['SECTION_ENABLE']):
    src += ['fm_section.c']

if GetDepend(['DEBUG_ENABLE']):
    src += ['fm_log.c']

# if GetDepend(['TIMER_ENABLE']):
#     src += ['fm_timer.c']

if GetDepend(['MEM_ENABLE']):
    if GetDepend(['MEM_MEMHEAP_ENABLE']):
        src += ['fm_memheap.c']
    else :
        src += ['fm_mem.c']

if GetDepend(['FIFO_ENABLE']):
    src += ['fm_fifo.c']
src += ['device.c']
path = [cwd + '/../include']

objs = DefineGroup('src', src, depend = [''], CPPPATH = path)

Return('objs')