from building import *

cwd = GetCurrentDir()
src = []

if GetDepend(['SECTION_ENABLE']):
    src += ['fm_section.c']

if GetDepend(['DEBUG_ENABLE']):
    src += ['fm_log.c']

if GetDepend(['TIMER_ENABLE']):
    src += ['fm_timer.c']

path = [cwd + '/../include']

objs = DefineGroup('src', src, depend = [''], CPPPATH = path)

Return('objs')