from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')

path = [cwd]

objs = DefineGroup('applications', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
