from building import *
import fmconfig

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
board_config.c
''')

path =  [cwd]
path += [cwd + '/config']

if GetDepend(['FM_USING_FAL']):
    src += Glob('port/fal_flash_onchip.c')
    path += [cwd + '/port']

startup_path_prefix = SDK_LIB

if fmconfig.PLATFORM in ['gcc']:
    src += [startup_path_prefix + '/hc32f4a0_ddl/drivers/cmsis/Device/HDSC/hc32f4xx/Source/GCC/startup_hc32f4a0.S']
elif fmconfig.PLATFORM in ['armcc', 'armclang']:
    src += [startup_path_prefix + '/hc32f4a0_ddl/drivers/cmsis/Device/HDSC/hc32f4xx/Source/ARM/startup_hc32f4a0.s']
elif fmconfig.PLATFORM in ['iccarm']:
    src += [startup_path_prefix + '/hc32f4a0_ddl/drivers/cmsis/Device/HDSC/hc32f4xx/Source/IAR/startup_hc32f4a0.s']

CPPDEFINES = ['HC32F4A0', 'FM_USING_LIBC']
group = DefineGroup('board', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
