from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src += ['../libraries/cmsis/Device/HDSC/hc32f4xx/Source/ARM/startup_hc32f4a0.s']

path = [cwd]

objs = DefineGroup('board', src, depend = [''], CPPPATH = path)

Return('objs')
